# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DTb7NA7ICq7rl4Ewo7jD1BEghtExYgj
"""

pip install chromadb sentence-transformers pandas gradio

from google.colab import files

print("Please upload your 'Rag_Project_Dataset.csv' file.")
uploaded = files.upload()

# Assuming the user uploads 'Rag_Project_Dataset.csv'
# You might need to adjust this if the user uploads a file with a different name
for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')
  uploaded_file_name = fn

if 'uploaded_file_name' in locals():
    print(f"File '{uploaded_file_name}' uploaded successfully. Proceeding to data processing.")
else:
    print("No file was uploaded. Please upload 'Rag_Project_Dataset.csv' to continue.")

import pandas as pd

# Read the uploaded CSV file into a DataFrame
df = pd.read_csv(uploaded_file_name)

# Display the first few rows and columns to verify
print("CSV file successfully loaded. Here's a preview of the data:")
print(df.head())
print(f"\nDataFrame shape: {df.shape}")

# Convert each row into a document string
def row_to_document(row):
    document_parts = []
    for col, value in row.items():
        # Skip TeamID as it's primarily an identifier, not descriptive content
        if col == 'TeamID':
            continue
        if pd.notna(value):
            document_parts.append(f"{col.replace(' ', '')}: {value}")
    return "\n".join(document_parts)

df['document'] = df.apply(row_to_document, axis=1)

print("\nExample of a generated document from a row:")
print(df['document'].iloc[0])

print("Data processing complete. Documents have been created from each row.")

from sentence_transformers import SentenceTransformer
import chromadb

print("Initializing Sentence Transformer model...")
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Model initialized.")

print("Generating embeddings for documents...")
# Get the list of documents from the DataFrame
documents = df['document'].tolist()
embeddings = model.encode(documents)
print(f"Generated {len(embeddings)} embeddings.")

print("Initializing ChromaDB client and collection...")
# Initialize ChromaDB client (in-memory for Colab)
chroma_client = chromadb.Client() # Renamed client to chroma_client

# Create or get the collection named 'team_knowledge'
collection_name = "team_knowledge"
try:
    collection = chroma_client.get_or_create_collection(name=collection_name)
    print(f"Collection '{collection_name}' ready.")
except Exception as e:
    print(f"Error creating or getting collection: {e}")
    # If the collection already exists and causes an error, try deleting and recreating
    chroma_client.delete_collection(name=collection_name)
    collection = chroma_client.get_or_create_collection(name=collection_name)
    print(f"Collection '{collection_name}' re-created.")

# Prepare metadata for ChromaDB
# As per the prompt, metadata should include TeamName, ProjectName, MemberName, Role, Status
# Adjust these to match your actual DataFrame column names if they differ
metadata_columns = ['TeamName', 'ProjectName', 'MemberName', 'Role', 'ProjectStatus'] # Assuming 'ProjectStatus' maps to 'Status'
metadatas = []
for index, row in df.iterrows():
    row_metadata = {}
    for col in metadata_columns:
        if col in row and pd.notna(row[col]):
            row_metadata[col] = str(row[col]) # Ensure metadata values are strings
    metadatas.append(row_metadata)

# Prepare IDs for ChromaDB (using sequential IDs for simplicity)
ids = [f"doc_{i}" for i in range(len(documents))]

print("Adding documents, embeddings, and metadata to ChromaDB...")
collection.add(
    documents=documents,
    embeddings=embeddings.tolist(), # Convert numpy array to list for ChromaDB
    metadatas=metadatas,
    ids=ids
)
print(f"Successfully added {collection.count()} documents to ChromaDB collection '{collection_name}'.")

print("ChromaDB storage complete. The knowledge base is now ready for querying!")

from sentence_transformers import SentenceTransformer
import chromadb
import pandas as pd

# Function to query the ChromaDB knowledge base
def query_knowledge_base(question, k=3):
    question_lower = question.lower()

    # --- Exact Match for TeamID ---
    if 'TeamID' in df.columns:
        matching_team = df[
            df['TeamID'].astype(str).str.lower()
            == question_lower
        ]
        if not matching_team.empty:
            team_name = matching_team.iloc[0]['TeamName']
            response = f"""
--- Team Details ---

Team ID: {matching_team.iloc[0]['TeamID']}
Team Name: {team_name}
"""
            members = matching_team[
                ['MemberName','Role']
            ].drop_duplicates()
            response += "\nMembers:\n"
            for _, row in members.iterrows():
                response += (
                    f"- {row['MemberName']} "
                    f"({row['Role']})\n"
                )
            return response

    # --- Exact Match for MemberID ---
    if 'MemberID' in df.columns:
        matching_member_id = df[
            df['MemberID'].astype(str).str.lower()
            == question_lower
        ]
        if not matching_member_id.empty:
            row = matching_member_id.iloc[0]
            return f"""
--- Member Details ---

Member ID: {row['MemberID']}
Member Name: {row['MemberName']}
Team: {row['TeamName']}
Role: {row['Role']}
Project: {row['ProjectName']}
Status: {row['ProjectStatus']}
Responsibilities: {row['Responsibilities']}
"""

    # --- Status Search ---
    if question_lower in [
        "completed",
        "ongoing"
    ]:
        projects = df[
            df['ProjectStatus']
            .str.lower() == question_lower
        ]
        response = (
            f"\nProjects with status "
            f"'{question}':\n\n"
        )
        for project in projects[
            'ProjectName'
        ].unique():
            response += f"- {project}\n"
        return response

    # --- Role Search ---
    roles = [
        "frontend developer",
        "backend developer",
        "data analyst",
        "project manager"
    ]
    if question_lower in roles:
        results = df[
            df['Role']
            .str.lower() == question_lower
        ]
        response = (
            f"\nMembers with role "
            f"{question}:\n\n"
        )
        for _, row in results.iterrows():
            response += (
                f"- {row['MemberName']} "
                f"({row['TeamName']})\n"
            )
        return response

    # --- Domain Search ---
    domains = [
        "business",
        "healthcare",
        "education",
        "retail",
        "agriculture",
        "cybersecurity",
        "transportation",
        "smart city",
        "hr tech",
        "events"
    ]
    if question_lower in domains:
        projects = df[
            df['ProjectDomain']
            .str.lower() == question_lower
        ]
        response = (
            f"\nProjects in "
            f"{question} domain:\n\n"
        )
        for _, row in projects.iterrows():
            response += (
                f"- {row['ProjectName']}"
                f" ({row['TeamName']})\n"
            )
        return response

    # --- 1. Exact Match for TeamName ---
    matching_teams = df[df['TeamName'].str.lower() == question_lower]
    if not matching_teams.empty:
        team_name = matching_teams['TeamName'].iloc[0]
        response = f"--- Details for Team: {team_name} ---\n"

        # Get unique projects and their statuses
        projects_info = matching_teams[['ProjectName', 'ProjectStatus']].drop_duplicates()
        response += "\nProjects:\n"
        for idx, row in projects_info.iterrows():
            response += f"- {row['ProjectName']} (Status: {row['ProjectStatus']})\n"

        # Get unique members and their roles
        members_info = matching_teams[['MemberName', 'Role']].drop_duplicates()
        response += "\nMembers:\n"
        for idx, row in members_info.iterrows():
            response += f"- {row['MemberName']} ({row['Role']})\n"

        return response

    # --- 2. Exact Match for MemberName ---
    matching_members = df[df['MemberName'].str.lower() == question_lower]
    if not matching_members.empty:
        member_name = matching_members['MemberName'].iloc[0]
        response = f"--- Details for Member: {member_name} ---\n"

        for idx, row in matching_members.drop_duplicates(subset=['MemberName', 'TeamName', 'ProjectName', 'Role', 'Responsibilities']).iterrows():
            response += f"\nTeam: {row['TeamName']}\n"
            response += f"Role: {row['Role']}\n"
            response += f"Project: {row['ProjectName']}\n"
            response += f"Responsibilities: {row['Responsibilities']}\n"
        return response

    # --- 3. Exact Match for ProjectName ---
    matching_projects = df[df['ProjectName'].str.lower() == question_lower]
    if not matching_projects.empty:
        project_name = matching_projects['ProjectName'].iloc[0]
        response = f"--- Details for Project: {project_name} ---\n"

        project_data = matching_projects.iloc[0] # Take first row for common project details
        response += f"\nTeam: {project_data['TeamName']}\n"
        response += f"Status: {project_data['ProjectStatus']}\n"
        response += f"Tech Stack: {project_data['TechStack']}\n"
        response += f"Problem Statement: {project_data['ProblemStatement']}\n"
        response += f"Solution: {project_data['Solution']}\n"

        # Get unique members for this project
        members_info = matching_projects[['MemberName', 'Role']].drop_duplicates()
        response += "\nMembers on Project:\n"
        for idx, row in members_info.iterrows():
            response += f"- {row['MemberName']} ({row['Role']})\n"
        return response

    # --- 4. Fallback to ChromaDB Semantic Search with RAG ---
    # Convert the question to an embedding
    question_embedding = model.encode([question]).tolist()[0]

    # Query ChromaDB for similar documents
    results = collection.query(
        query_embeddings=[question_embedding],
        n_results=k,
        include=['documents', 'metadatas']
    )

    # Build context from the retrieved documents
    if not results['documents'][0]:
        return "No relevant information found via semantic search."

    context = "\n\n".join(
        [doc for doc in results['documents'][0] if doc] # Filter out any potential empty documents
    )

    # Gemini Prompt
    prompt = f"""
You are a Team Knowledge Assistant.

Answer ONLY from the provided context.

Context:
{context}

Question:
{question}

Provide a clear and concise answer.
"""
    # Use the globally available 'gemini_client' for Gemini
    response = gemini_client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

pip install -q google-generativeai

from google import genai

# Paste your Gemini API Key here
import os

API_KEY = os.getenv("GEMINI_API_KEY")
gemini_client = genai.Client(api_key=API_KEY) # Renamed client to gemini_client

print("Gemini Connected Successfully!")



while True:
    question = input("Ask a question: ")

    if question.lower() == "exit":
        break

    answer = query_knowledge_base(question)

    print("\nAnswer:")
    print(answer)
    print("\n" + "="*50 + "\n")

